openapi: 3.0.0
info:
  title: Social App
  description: First Social App to deploy - Manohar
  version : 1.0.1

servers:
  - url: http://localhost:3000/api/v1
    description: Localhost version of Social App
  - url: https://localhost:3000/api/v1
    description: Dummy API url, it doesn't work

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary: Returns username, followers and follows
      responses:
        '200':
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: integer
                  follows:
                    type: integer
    post:
      summary: Returns username, followers and follows
      responses:
        '200':
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: integer
                  follows:
                    type: integer
  /{token}:
    get:
      summary: returns whatever is in params / url
      parameters:
        - name: token
          default: 5
          in: path
          schema:
            type: string
      responses:
        '200':
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  param:
                    type: string